import tour1 from "../../assets/tour1.png"
import tour2 from "../../assets/tour2.png"
import tour3 from "../../assets/tour3.png"
import tour4 from "../../assets/tour4.png"
import tour5 from "../../assets/tour5.png"
import tour6 from "../../assets/tour6.png"
import tour7 from "../../assets/tour7.png"
import tour8 from "../../assets/tour8.png"
import tour9 from "../../assets/tour9.png"
const rome = 'https://cdn-ilanhlf.nitrocdn.com/AzmJrPQohnwWLiYOIRijiymirQDdSgxs/assets/images/optimized/rev-1120628/theluxuryeditor.com/wp-content/uploads/2022/01/124801993.jpg'
const berlin = 'https://www.shutterstock.com/image-photo/brandenburg-gate-illuminated-sunset-berlin-600nw-2323529337.jpg'
const london = 'https://img.freepik.com/free-photo/big-ben-houses-parliament-london-uk_268835-1400.jpg?semt=ais_hybrid&w=740&q=80'
const venice = 'https://media.istockphoto.com/id/1290101421/photo/venice-on-rainy-day.jpg?s=612x612&w=0&k=20&c=28SHoE_oc-6e-ZVSqJ5qWLNqysTSJs7-utbEDtXxcds='
const prague = 'https://images.contentstack.io/v3/assets/blt06f605a34f1194ff/bltdf62f93083b67189/685edf66018093916bfacac1/BCC-2024-EXPLORER-PRAGUE-HOW-TO-AVOID-CROWDS-HEADER_MOBILE.jpg?format=webp&auto=avif&quality=60&crop=1%3A1&width=425'
const madrid = 'https://thumbs.dreamstime.com/b/madrid-spain-gran-via-cityscape-calle-de-alcala-50762433.jpg'
const paris = 'https://t3.ftcdn.net/jpg/00/44/31/30/360_F_44313077_sGmwyXISpFVsCmpKvnwExPq6FF3qsHda.jpg'
const amsterdam = 'https://resize.tripster.ru/UU4p8FoLHLn6_Hz9IWeeDxgPWXo=/fit-in/384x289/filters:no_upscale()/https://cdn.tripster.ru/photos/9ed91c8b-b5a8-400f-9e37-884cd9f31772.jpg'
const switz = 'https://production.media.dcx.clubmed/?url=https%3A%2F%2Fassets.dream.clubmed%2Fpm_7531_589_589941-3f5ivsx967-swhr.jpg&format=webp&width=300&height=300&quality=70'
const vienna = 'https://www.traveloffpath.com/wp-content/uploads/2023/05/Schonbrunn-palace-in-Vienna.jpg.webp'
const santorini = 'https://navigosha.com/pic/city/santorini.jpg'
const budapest = 'https://media.istockphoto.com/id/1172437911/photo/budapest-hungary-the-main-tower-of-the-famous-fishermans-bastion-from-above.jpg?s=612x612&w=0&k=20&c=njiP9o0pZYKpUiAQdq1gMHllQK34-Is5gqjZ_e_EGu0='

export const tours = [
    {
        id: 1,
        title: "Ireland Wild Nature",
        author: "Karineside",
        price: 548,
        oldPrice: 699,
        rating: 4.9,
        date: "Tue, Jul 20 – Fri, Jul 23",
        img: tour9,
        category: "Cheapest",
    },
    {
        id: 10,
        title: "Luxury Rome Escape",
        author: "Karineside",
        price: 1200,
        oldPrice: 1450,
        rating: 5.0,
        date: "Fri, Apr 8 – Mon, Apr 11",
        img: rome,
        category: "Best",
    },
    {
        id: 15,
        title: "Berlin Express",
        author: "Karineside",
        price: 300,
        oldPrice: 450,
        rating: 4.5,
        date: "Mon, Sep 5 – Tue, Sep 6",
        img: berlin,
        category: "Quickest",
    },
    {
        id: 2,
        title: "Canyon Adventure",
        author: "Karineside",
        price: 620,
        oldPrice: 720,
        rating: 4.8,
        date: "Mon, Aug 2 – Thu, Aug 5",
        img: tour1,
        category: "Cheapest",
    },
    {
        id: 16,
        title: "London in 2 Days",
        author: "Karineside",
        price: 400,
        oldPrice: 550,
        rating: 4.6,
        date: "Sat, Oct 15 – Sun, Oct 16",
        img: london,
        category: "Quickest",
    },
    {
        id: 3,
        title: "Beach Paradise",
        author: "Karineside",
        price: 499,
        oldPrice: 650,
        rating: 4.7,
        date: "Fri, Sep 10 – Mon, Sep 13",
        img: tour2,
        category: "Cheapest",
    },
    {
        id: 11,
        title: "Venice Gondola Nights",
        author: "Karineside",
        price: 980,
        oldPrice: 1100,
        rating: 4.9,
        date: "Wed, May 18 – Sat, May 21",
        img: venice,
        category: "Best",
    },
    {
        id: 17,
        title: "Prague Weekend",
        author: "Karineside",
        price: 350,
        oldPrice: 500,
        rating: 4.7,
        date: "Fri, Nov 11 – Sun, Nov 13",
        img: prague,
        category: "Quickest",
    },
    {
        id: 4,
        title: "Golden Gate Tour",
        author: "Karineside",
        price: 700,
        oldPrice: 850,
        rating: 4.9,
        date: "Sat, Oct 1 – Tue, Oct 4",
        img: tour3,
        category: "Cheapest",
    },
    {
        id: 18,
        title: "Madrid Fast Trip",
        author: "Karineside",
        price: 420,
        oldPrice: 560,
        rating: 4.5,
        date: "Thu, Dec 1 – Sat, Dec 3",
        img: madrid,
        category: "Quickest",
    },
    {
        id: 12,
        title: "Paris Eiffel Dream",
        author: "Karineside",
        price: 1400,
        oldPrice: 1600,
        rating: 5.0,
        date: "Tue, Jun 14 – Fri, Jun 17",
        img: paris,
        category: "Best",
    },
    {
        id: 5,
        title: "Mountain Rivers",
        author: "Karineside",
        price: 560,
        oldPrice: 640,
        rating: 4.6,
        date: "Wed, Nov 17 – Sat, Nov 20",
        img: tour4,
        category: "Cheapest",
    },
    {
        id: 19,
        title: "Amsterdam Short Tour",
        author: "Karineside",
        price: 380,
        oldPrice: 500,
        rating: 4.6,
        date: "Tue, Jan 3 – Wed, Jan 4",
        img: amsterdam,
        category: "Quickest",
    },
    {
        id: 13,
        title: "Swiss Alps Premium",
        author: "Karineside",
        price: 1550,
        oldPrice: 1800,
        rating: 5.0,
        date: "Mon, Jul 25 – Thu, Jul 28",
        img: switz,
        category: "Best",
    },
    {
        id: 6,
        title: "City Sunset View",
        author: "Karineside",
        price: 580,
        oldPrice: 710,
        rating: 4.8,
        date: "Thu, Dec 9 – Sun, Dec 12",
        img: tour5,
        category: "Cheapest",
    },
    {
        id: 20,
        title: "Vienna Express",
        author: "Karineside",
        price: 360,
        oldPrice: 480,
        rating: 4.7,
        date: "Mon, Feb 6 – Tue, Feb 7",
        img: vienna,
        category: "Quickest",
    },
    {
        id: 14,
        title: "Santorini Deluxe",
        author: "Karineside",
        price: 1300,
        oldPrice: 1500,
        rating: 4.9,
        date: "Fri, Aug 19 – Mon, Aug 22",
        img: santorini,
        category: "Best",
    },
    {
        id: 7,
        title: "Cargo Ship Tour",
        author: "Karineside",
        price: 610,
        oldPrice: 760,
        rating: 4.7,
        date: "Mon, Jan 10 – Thu, Jan 13",
        img: tour6,
        category: "Cheapest",
    },
    {
        id: 21,
        title: "Budapest Flash Tour",
        author: "Karineside",
        price: 330,
        oldPrice: 450,
        rating: 4.5,
        date: "Fri, Mar 10 – Sat, Mar 11",
        img: budapest,
        category: "Quickest",
    },
    {
        id: 8,
        title: "Snowy Mountains",
        author: "Karineside",
        price: 590,
        oldPrice: 680,
        rating: 4.9,
        date: "Tue, Feb 15 – Fri, Feb 18",
        img: tour7,
        category: "Cheapest",
    },
    {
        id: 9,
        title: "Desert Canyon Sky",
        author: "Karineside",
        price: 530,
        oldPrice: 600,
        rating: 4.6,
        date: "Sat, Mar 12 – Tue, Mar 15",
        img: tour8,
        category: "Cheapest",
    },
];